name: foodiefinds
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.2

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  location: ^7.0.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

